version: '2'
plugins:
  rubocop:
    enabled: false
    channel: rubocop-0-73
  eslint:
    enabled: false
  csslint:
    enabled: true
  scss-lint:
    enabled: true
  brakeman:
    enabled: false
checks:
  similar-code:
    enabled: false
  method-count:
    enabled: true
    config:
      threshold: 32
  file-lines:
    enabled: true
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - 'spec/'
  - '**/specs/'
  - 'db/*'
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'public/**/*'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'lib/tasks/auto_annotate_models.rake'
  - 'app/test-matchers.js'
  - 'docs/*'
  - '**/*.md'
  - '**/*.yml'
